In [8]:
import numpy as np

r = int(input("Enter rows: "))
c = int(input("Enter columns: "))

trials = np.zeros(r, dtype=int)

# Hidden matrix
hidden = np.random.randint(1, 20, size=(r, c))

print("\nHidden matrix (for testing):")
print(hidden)

for i in range(r):
    print(f"\nGuessing for Row {i + 1}")
    while True:
        trials[i] += 1
        guess = input(
            f"Enter your {c} guesses separated by space: "
        ).split()

        # convert input to integer numpy array
        guess = np.array(guess, dtype=int)

        if np.array_equal(guess, hidden[i]):
            print("✅ Correct!")
            break
        else:
            print("❌ Incorrect, try again.")

print("\n🎯 Number of trials for each row:")
for i in range(r):
    print(f"Row {i + 1}: {trials[i]} trials")



Hidden matrix (for testing):
[[16  3 10]
 [19 15  4]
 [ 7  1  6]]

Guessing for Row 1
❌ Incorrect, try again.
❌ Incorrect, try again.
❌ Incorrect, try again.
✅ Correct!

Guessing for Row 2
✅ Correct!

Guessing for Row 3
✅ Correct!

🎯 Number of trials for each row:
Row 1: 4 trials
Row 2: 1 trials
Row 3: 1 trials
