In [9]:
import numpy as np

arr = np.random.rand(4,4,4)
norm_axis0 = arr / np.linalg.norm(arr, axis=0, keepdims=True)
norm_axis1 = arr / np.linalg.norm(arr, axis=1, keepdims=True)
norm_axis2 = arr / np.linalg.norm(arr, axis=2, keepdims=True)
print("Normalized along axis 0:\n", norm_axis0)
print("Normalized along axis 1:\n", norm_axis1)
print("Normalized along axis 2:\n", norm_axis2)

Normalized along axis 0:
 [[[0.30417589 0.20429861 0.62228447 0.62014268]
  [0.4976603  0.23763409 0.40032181 0.72059393]
  [0.50207221 0.24622274 0.88396797 0.59570194]
  [0.80150488 0.40771914 0.65577471 0.55548767]]

 [[0.07816696 0.90680556 0.45971931 0.42894009]
  [0.06108478 0.72121508 0.4901151  0.00121964]
  [0.07490621 0.79527287 0.29052313 0.68599858]
  [0.40637432 0.42718523 0.6748028  0.12572912]]

 [[0.30266381 0.36457442 0.46152289 0.62363348]
  [0.03222702 0.62291859 0.06277845 0.69323043]
  [0.85002154 0.00233963 0.36379769 0.23794166]
  [0.42506735 0.45485985 0.33637682 0.23382642]]

 [[0.89986753 0.055238   0.43407006 0.20619101]
  [0.864618   0.18801935 0.77174381 0.01320854]
  [0.14062694 0.55399455 0.04299044 0.34340778]
  [0.10847851 0.66661863 0.03809652 0.78800434]]]
Normalized along axis 1:
 [[[0.32846608 0.33556954 0.59761943 0.67767122]
  [0.57536671 0.41115878 0.31305791 0.49777006]
  [0.51612254 0.39774852 0.50031074 0.2972713 ]
  [0.54284501 0.74842345 0.5